window.__tcs=1;
/* ===== TCS HTQLAN – cấu hình ảnh & giao diện =====
   CFG.photos = true: web tự nạp ảnh thật trong assets/img/photos/ (xem README). Thiếu ảnh sẽ dùng hình minh họa. */
const CFG={photos:true},IMG={logo:'assets/img/logo.png',sq:'assets/img/sq.png',banner:'assets/img/banner.jpg'};
try{const t=localStorage.getItem('tcs-theme');if(t)document.documentElement.dataset.theme=t}catch(e){}
const $=s=>document.querySelector(s),vnd=n=>Math.round(n).toLocaleString('vi-VN')+' đ',fmt=d=>d?new Date(d).toLocaleString('vi-VN',{hour12:false}):'—',now=()=>Date.now(),H=36e5;
const GRACE=15,TYPES=['Xe tải nhỏ','Xe bán tải','Xe container'];
let S={
 lots:[
  {id:'LH-2601',plate:'51C-123.45',type:TYPES[0],ex:1,reg:1,driver:'Nguyễn Văn An',owner:'Cty Thành Đạt',sync:'Đã đồng bộ'},
  {id:'LH-2602',plate:'50H-678.90',type:TYPES[2],ex:1,reg:1,driver:'Trần Minh Hải',owner:'Cty Phú Gia',sync:'Đã đồng bộ'},
  {id:'LH-2603',plate:'60C-555.12',type:TYPES[1],ex:0,reg:1,driver:'Lê Quốc Bảo',owner:'Cty An Phát',sync:'Đã đồng bộ'},
  {id:'LH-2604',plate:'61C-246.80',type:TYPES[0],ex:1,reg:0,driver:'—',owner:'Cty Hoàng Long',sync:'Đã đồng bộ'},
  {id:'LH-2605',plate:'51D-909.09',type:TYPES[2],ex:1,reg:1,driver:'Võ Thanh Tùng',owner:'Cty Nam Việt',sync:'Đã đồng bộ'},
  {id:'LH-2606',plate:'72C-111.22',type:TYPES[1],ex:1,reg:1,driver:'Phạm Đức Long',owner:'Cty Đại Dương',sync:'Đã đồng bộ'}],
 sess:[
  {id:'PH-0001',plate:'50H-678.90',lot:'LH-2602',type:TYPES[2],inAt:now()-5*H,st:'Đang đỗ',paid:0,due:0,ch:''},
  {id:'PH-0002',plate:'51D-909.09',lot:'LH-2605',type:TYPES[2],inAt:now()-1.5*H,st:'Đang đỗ',paid:0,due:0,ch:''},
  {id:'PH-0003',plate:'72C-111.22',lot:'LH-2606',type:TYPES[1],inAt:now()-4*H,st:'Đã thanh toán',paid:120000,due:120000,ch:'QR',rc:'BL-000101',payAt:now()-.4*H}],
 prices:[],sur:[{id:'PP-01',name:'Phí mái che',after:180,fee:50000,on:1}],
 users:[{u:'baove01',n:'Đặng Văn Bảo',r:'Bảo vệ cổng',on:1},{u:'thungan01',n:'Ngô Thu Hà',r:'Thu ngân quầy',on:1},{u:'quanly01',n:'Lý Hoàng Nam',r:'Quản lý an ninh',on:1},{u:'admin',n:'Quản trị hệ thống',r:'Quản trị hệ thống',on:1}],
 exc:[{t:now()-26*H,who:'baove01',lane:'Lane vào 1',plate:'61C-246.80',why:'Lệnh miễn trừ của Trưởng ca',kind:'Mở barrier thủ công (vào)'}],
 api:[],rcN:102,pdN:3,lane:{in:0,out:0},tab:'Cash'};
const base={[TYPES[0]]:[15e3,40e3,80e3,150e3],[TYPES[1]]:[20e3,50e3,100e3,180e3],[TYPES[2]]:[30e3,80e3,150e3,280e3]},rg=[[0,60],[60,180],[180,720],[720,99999]];
TYPES.forEach(t=>rg.forEach((r,i)=>S.prices.push({id:'BG-'+t.slice(3,5).toUpperCase()+(i+1),type:t,from:r[0],to:r[1],price:base[t][i]})));
for(let i=0;i<8;i++){const ok=i%5;S.api.push({t:now()-i*6e4*5,sys:i%3==2?'Camera AI':'COSYS',ip:i%3==2?'10.10.2.21':'10.10.1.5',ok:i!=4,msg:i==4?'Timeout 30s':'OK – 6 bản ghi'})}
const feeOf=(s,end)=>{const m=Math.max(1,Math.ceil(((end||now())-s.inAt)/6e4)),p=S.prices.find(x=>x.type==s.type&&m>=x.from&&m<x.to),base=p?p.price:0,su=S.sur.filter(x=>x.on&&m>x.after);return{m,base,su,sf:su.reduce((a,b)=>a+b.fee,0),tot:base+su.reduce((a,b)=>a+b.fee,0)}};
const dur=m=>Math.floor(m/60)+' giờ '+m%60+' phút';
const toast=m=>{const t=$('#toast');t.innerHTML='';const s=document.createElement('span');s.textContent=m;const b=document.createElement('button');b.textContent='Đóng';b.onclick=()=>t.classList.remove('on');t.append(s,b);t.setAttribute('role','status');t.classList.add('on');clearTimeout(toast.i);toast.i=setTimeout(()=>t.classList.remove('on'),4000)};
const tag=(t,c='')=>`<span class="tg ${c}">${t}</span>`,plate=p=>`<span class="plate">${p}</span>`;
function modal(html){const m=document.createElement('div');m.className='mo';m.innerHTML=`<div class="c mdlg" role="dialog" aria-modal="true">${html}</div>`;const d=m.firstChild,t=d.querySelector('h3');if(t){t.id='dt'+Date.now();d.setAttribute('aria-labelledby',t.id)}m.onmousedown=e=>{if(e.target==m)cm()};m._prev=document.activeElement;document.body.append(m);const f=d.querySelector('input,select,textarea,button');if(f)f.focus();return m}
window.cm=()=>document.querySelectorAll('.mo:not(.out)').forEach(m=>{m.classList.add('out');setTimeout(()=>{m.remove();if(m._prev&&m._prev.focus&&document.contains(m._prev))m._prev.focus()},150)});
addEventListener('keydown',e=>{const m=[...document.querySelectorAll('.mo:not(.out)')].pop();if(!m)return;if(e.key=='Escape'){cm();return}if(e.key=='Tab'){const f=[...m.querySelectorAll('button,input,select,textarea')].filter(x=>!x.disabled);if(!f.length)return;const a=f[0],z=f[f.length-1];if(e.shiftKey&&document.activeElement==a){e.preventDefault();z.focus()}else if(!e.shiftKey&&document.activeElement==z){e.preventDefault();a.focus()}}});
const lotBy=p=>S.lots.find(l=>l.plate==p),live=()=>S.sess.filter(s=>s.st!='Đã đóng');
const MENU=[['Tổng quan',[['dash','Bảng điều khiển']]],['Module I – Xe vào',[['in','Kiểm soát lane vào'],['mon','Giám sát camera & radar'],['lots','Danh mục lô hàng'],['recv','Thông tin nhận hàng']]],
['Module II – Thanh toán',[['pay','Quầy thu ngân'],['txn','Giao dịch thanh toán'],['prices','Bảng giá sân đỗ'],['sur','Phụ phí dịch vụ']]],['Module III – Xe ra',[['out','Kiểm soát lane ra'],['alert','Cảnh báo xe chưa thanh toán']]],
['Module IV – Quản trị',[['users','Phân quyền người dùng'],['hist','Lịch sử & ngoại lệ'],['api','Kết nối API']]],['Module V – Báo cáo',[['rev','Báo cáo doanh thu'],['trf','Báo cáo lưu lượng xe']]]];
const P={};let cur='dash';
function go(k){cur=k;location.hash=k;$('#nav').innerHTML='<div class="brand"><img src="'+IMG.sq+'" alt="TCS"><b>TCS – HTQLAN<small>Quản lý an ninh cổng</small></b></div>'+(me?'<a tabindex=0 class="me" onclick="logout()">← Chọn lại vai trò<br><small>'+me.n+' · '+me.r+'</small></a>':'')+vis().map(([g,a])=>`<h6>${g}</h6>`+a.map(([k,n])=>`<a tabindex=0 class="${k==cur?'on':''}" onclick="go('${k}')">${n}</a>`).join('')).join('')+foot();$('#app').innerHTML=(!me?P.login:can(k)?P[k]:P.deny)();document.body.classList.toggle('no-nav',!me);document.body.classList.toggle('nav-off',!!me&&navOff);window.scrollTo(0,0)}
/* Ẩn/hiện thanh menu (chỉ khi đã chọn vai trò) */
let navOff=false;try{navOff=localStorage.getItem('tcs_nav_off')=='1'}catch(e){}
window.toggleNav=()=>{navOff=!navOff;try{localStorage.setItem('tcs_nav_off',navOff?'1':'0')}catch(e){}document.body.classList.toggle('nav-off',navOff);const b=$('#navBtn');if(b){b.setAttribute('aria-expanded',String(!navOff));b.title=navOff?'Hiện thanh menu':'Ẩn thanh menu'}};
const R=()=>go(cur);

/* ===== Ảnh minh họa thực tế cho từng chức năng (Wikimedia Commons, giấy phép tự do) ===== */
const PH={
dash:['Kho hàng hóa hàng không','Máy bay hàng hóa hạ cánh tại sân bay Tân Sơn Nhất','Blue Stahli Luân','CC BY 2.0'],
'lane-in':['Cổng vào khu nhận hàng','Lane kiểm soát xe tải tại nhà ga hàng hóa','N509FZ','CC BY-SA 4.0'],
'lane-out':['Chốt bảo vệ và barrier lane ra','Bảo vệ trực cổng, barrier chỉ mở khi xe đủ điều kiện','PattayaPatrol','CC BY-SA 4.0'],
mon:['Camera AI giám sát lane','Camera nhận diện biển số và tủ thiết bị tại cột lane','RickySpanish','CC BY-SA 4.0'],
lots:['Lô hàng trên ULD/pallet','Hàng hóa đóng pallet chờ xuất kho, đồng bộ trạng thái từ COSYS','Aero Icarus','CC BY-SA 2.0'],
recv:['Nhận hàng tại dock kho','Xe nâng bốc xếp hàng lên container của chủ hàng','Goterrestrial','CC BY 4.0'],
pay:['Thanh toán quét mã QR','Thiết bị thanh toán tại quầy, hỗ trợ VietQR / VNPay','Sonixrulerz','CC BY-SA 4.0'],
txn:['Giao dịch qua máy POS','Mỗi giao dịch gắn mã biên lai và phiên đỗ','Basile Morin','CC BY-SA 4.0'],
prices:['Sân đỗ xe tải','Giá đỗ tính theo loại xe và thời gian đỗ','Ildar Sagdejev (Specious)','CC BY-SA 4.0'],
sur:['Khu đỗ có mái che','Phụ phí dịch vụ cộng tự động khi vượt ngưỡng thời gian','Flicker02','CC BY-SA 4.0'],
alert:['Barrier giữ xe chưa thanh toán','Lane ra khóa barrier, cảnh báo đến bảo vệ và thu ngân','AgainErick','CC BY-SA 4.0'],
users:['Chốt an ninh cổng','Bảo vệ, thu ngân, quản lý an ninh và quản trị theo vai trò','Citobun','CC BY-SA 3.0'],
hist:['Trung tâm giám sát','Tra cứu lịch sử hình ảnh vào/ra và các lần mở barrier thủ công','Mark Yeomans','CC BY-SA 4.0'],
api:['Hạ tầng tích hợp','Máy chủ kết nối COSYS, Camera AI, radar, barrier và Banking Gateway','Tony Webster','CC BY 2.0'],
rev:['Đối soát doanh thu','Báo cáo theo ngày, ca và kênh thanh toán','U.S. Department of Agriculture','Public domain'],
trf:['Lưu lượng xe container','Thống kê lượt xe vào/ra theo khung giờ','BlackCab','CC BY-SA 4.0']};
const PHPOS={"pay": "50% 8%", "mon": "50% 20%", "txn": "50% 30%", "api": "50% 45%", "rev": "50% 40%", "lots": "50% 62%", "recv": "50% 50%", "alert": "50% 62%", "users": "50% 45%", "sur": "50% 62%", "prices": "50% 55%", "trf": "50% 45%", "hist": "50% 50%", "dash": "50% 40%", "lane-in": "50% 60%", "lane-out": "50% 60%"};
const phSrc=k=>'assets/img/photos/'+k+'.jpg';
const credit=k=>`<small class="cr">Ảnh: ${PH[k][2]} / Wikimedia Commons, ${PH[k][3]}</small>`;
const phB=k=>PH[k]?`<div class="hero ph"><img src="${phSrc(k)}" style="object-position:${PHPOS[k]||'center'}" alt="${PH[k][0]}" onerror="this.parentNode.remove()"><div><b>${PH[k][0]}</b><br>${PH[k][1]}</div>${credit(k)}</div>`:'';
const PHMAP={in:null,out:null,dash:null};
const strip=()=>`<div class="g g4 strip">${[['lane-in','in','Lane vào'],['lots','lots','Lô hàng'],['pay','pay','Thu ngân'],['lane-out','out','Lane ra']].map(([k,g,n])=>`<a class="tile" tabindex=0 onclick="go('${g}')"><img src="${phSrc(k)}" alt="${n}"><span>${n}</span></a>`).join('')}</div>`;
const head=(t,d,x='')=>`<div class="top"><div class="tl">${me?`<button id="navBtn" class="nb" onclick="toggleNav()" aria-controls="nav" aria-expanded="${!navOff}" title="${navOff?'Hiện thanh menu':'Ẩn thanh menu'}"><i></i><i></i><i></i></button>`:''}<div><h2>${t}</h2><p>${d}</p></div></div><div class="row">${x}<button class="s" onclick="tt()">◐ Sáng/Tối</button>${me?'<button class="s" onclick="logout()">← Chọn lại vai trò</button>':''}</div></div>`+(PHMAP[cur]===null?'':phB(cur));
const tbl=(h,rows)=>`<div class="tw"><table><tr>${h.map(x=>`<th>${x}</th>`).join('')}</tr>${rows.length?rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join(''):`<tr><td colspan=${h.length} style="color:var(--mu)">Chưa có dữ liệu</td></tr>`}</table></div>`;
const st=(ok,t,d='')=>`<div class="step ${ok}"><b>${ok=='ok'?'✔':ok=='er'?'✖':'…'}</b><div><b>${t}</b><div style="color:var(--mu)">${d}</div></div></div>`;
const bars=(a,f=x=>x)=>{const m=Math.max(...a.map(x=>x[1]));return a.map(([l,v])=>`<div class="bar"><span style="width:64px;color:var(--mu)">${l}</span><i style="width:${Math.max(2,v/m*60)}%"></i><b>${f(v)}</b></div>`).join('')};

/* DASH */
P.dash=()=>{const l=live(),rev=S.sess.filter(s=>s.payAt).reduce((a,s)=>a+s.paid,0)+ 8420000;
return head('Bảng điều khiển','Tình hình vận hành cổng hôm nay')+heroH()+strip()+`<div class="g g4"><div class="c k"><b>${l.length}</b><span>Xe đang trong bãi</span></div><div class="c k"><b>${vnd(rev)}</b><span>Doanh thu hôm nay</span></div><div class="c k"><b>${S.exc.filter(e=>e.kind.startsWith('Mở')).length}</b><span>Lượt mở barrier thủ công</span></div><div class="c k"><b>${S.lots.filter(x=>x.ex&&x.reg).length}/${S.lots.length}</b><span>Lô hàng đủ điều kiện vào</span></div></div>
<div class="g g2 mt"><div class="c"><h3>Xe đang trong bãi</h3>${tbl(['Biển số','Loại xe','Giờ vào','Trạng thái'],l.map(s=>[s.plate,s.type,fmt(s.inAt),tag(s.st,s.st=='Đang đỗ'?'wa':'ok')]))}</div>
<div class="c"><h3>Kết nối hệ thống</h3>${st('ok','COSYS','Online – đồng bộ gần nhất 2 phút trước')}${st('ok','Camera AI / Radar / Barrier','Online – 2 lane hoạt động')}${st('ok','Banking Gateway (VietQR/VNPay)','Online')}</div></div>`};

/* LANE VÀO */

/* ===== Kết quả xử lý lane: ảnh camera ANPR ===== */
const VEH={'Xe tải nhỏ':1,'Xe bán tải':4,'Xe container':3};
/* vị trí biển số trong từng ảnh xe (% trái, % trên, % rộng, % cao, màu nền) */
const PLP={1:[10.3,74.6,6.9,6.6,''],2:[64.8,84.6,5.4,3.9,''],3:[10.2,67.7,4.4,3.9,'y'],4:[67.7,84.6,8.6,6,'']};
const tsF=()=>new Date().toLocaleString('vi-VN',{hour12:false});
const conf=p=>94+[...p].reduce((a,c)=>a+c.charCodeAt(0),0)%6;
const snap=(k,p,type,ok,body,o={})=>{const v=type?VEH[type]||1:2,[x,y,w,h,c]=PLP[v],cam=k=='in'?'CAM-IN-01 · Lane vào 1':'CAM-OUT-01 · Lane ra 1',
cf=o.nf?'—':conf(p)+'%',vt=ok?(k=='in'?'ĐỦ ĐIỀU KIỆN · MỞ BARRIER':'CHO XE RA · MỞ BARRIER'):'KHÔNG ĐẠT · GIỮ BARRIER',
vs=ok?(k=='in'?'Đã tạo phiên đỗ và bắt đầu tính phí bãi':'Đã đóng phiên, lưu ảnh check-out'):(o.why||'Bảo vệ xử lý theo quy trình');
return `<div class="snap"><img src="assets/img/photos/vehicles/veh-${v}.jpg" alt="Ảnh camera chụp xe ${p}">
<div class="hud"><span class="rec">${cam}</span><span>${tsF()}</span></div>
<span class="lp ${c}" style="left:${x}%;top:${y}%;width:${w}%;height:${h}%"><b style="font-size:${(w*0.19).toFixed(2)}cqw">${p}</b></span>
<span class="bb ${ok?'':'er'}" style="left:${x-1.2}%;top:${y-2.2}%;width:${w+2.4}%;height:${h+4.4}%"><i>ANPR ${p} · ${cf}</i></span>
</div><div class="verdict ${ok?'':'er'}"><span class="ic">${ok?'✔':'✖'}</span><div>${vt}<small>${vs}</small></div></div>
<div class="meta"><div><small>Biển số nhận diện</small><b>${p}</b></div><div><small>Loại xe</small><b>${type||'Chưa phân loại'}</b></div><div><small>Độ tin cậy ANPR</small><b>${cf}</b></div><div><small>Barrier</small><b style="color:var(--${ok?'ok':'er'})">${ok?'Đang mở':'Giữ đóng'}</b></div></div>
<div class="shots"><div class="shot"><div class="im">${plSvg(p)}</div><span>Ảnh biển số <b>${k=='in'?'Check-in':'Check-out'}</b></span></div>
<div class="shot"><div class="im">${faceSvg()}</div><span>Tài xế ${k=='out'?'<b style="color:var(--'+(o.face?'er':'ok')+')">'+(o.face?'Không khớp':'Khớp')+'</b>':'<b>Đã chụp</b>'}</span></div>
<div class="shot"><div class="im"><div class="bar2 ${ok?'ok':'er'}">${ok?'▲ BARRIER MỞ':'■ BARRIER ĐÓNG'}</div></div><span>Trạng thái <b>${k=='in'?'Lane vào':'Lane ra'}</b></span></div></div>
<h3 class="mt">Các bước kiểm tra</h3>${body}`};
const waitR=k=>`<div class="snap wait"><img src="assets/img/photos/lane-${k}.jpg" alt="Lane ${k=='in'?'vào':'ra'} đang chờ xe"><div class="hud"><span class="rec">${k=='in'?'CAM-IN-01 · Lane vào 1':'CAM-OUT-01 · Lane ra 1'}</span><span>LIVE</span></div><div class="radar"></div><div class="wt"><b>Đang chờ xe vào vùng nhận diện…</b><span>Radar sẵn sàng · Camera ANPR online · Barrier đóng</span></div></div>
<div class="pipe">${(k=='in'?[['Radar','Phát hiện xe'],['Camera AI','Đọc biển số'],['COSYS','Đối chiếu lô hàng'],['Barrier','Mở / giữ']]:[['Camera AI','Đọc biển số'],['Phiên vào','Đối chiếu'],['Thanh toán','Kiểm tra phí'],['Barrier','Mở / giữ']]).map(([a,b])=>`<span><b>${a}</b>${b}</span>`).join('')}</div>`;
let inR=null;
P.in=()=>{const opts=S.lots.map(l=>`<option>${l.plate}</option>`).join('')+'<option>29A-999.99</option>';
return head('Kiểm soát lane vào','Radar → Camera AI đọc biển số → đối chiếu COSYS → barrier')+`<div class="g g2"><div class="c"><h3>Mô phỏng xe tiến vào lane</h3><label>Biển số camera đọc được</label><div class="row"><select id="ip">${opts}</select><button onclick="scanIn()">Radar phát hiện xe</button></div><p style="color:var(--mu)">Thử: 51C-123.45 (đạt), 60C-555.12 (chưa xuất kho), 61C-246.80 (chưa đăng ký), 29A-999.99 (không có trong COSYS).</p><div class="mt">${pic('lane-in',laneSvg('in'),'Camera lane vào 1')}</div><div style="margin-top:12px">Barrier lane vào</div><div class="gate ${S.lane.in?'open':''}"></div></div>
<div class="c"><h3>Kết quả xử lý</h3>${inR?inR:waitR('in')}</div></div>
<div class="c mt"><h3>Lượt vào gần đây</h3>${tbl(['Mã phiên','Biển số','Lô hàng','Giờ check-in','Trạng thái'],S.sess.slice().reverse().slice(0,6).map(s=>[s.id,s.plate,s.lot,fmt(s.inAt),tag(s.st)+(s.exIn||s.exOut?' '+tag('Ngoại lệ','er'):'')]))}</div>`};
window.newSess=(p,l,ex)=>S.sess.push({id:'PH-'+String(S.sess.length+1).padStart(4,'0'),plate:p,lot:l?l.id:'—',type:l?l.type:TYPES[0],inAt:now(),st:'Đang đỗ',paid:0,due:0,ch:'',exIn:ex,imgIn:1});
window.scanIn=()=>{const p=$('#ip').value,l=lotBy(p),dup=live().find(s=>s.plate==p),used=l&&l.used,ok=l&&l.reg&&l.ex&&!dup&&!used;
let h=st('ok','Radar phát hiện xe · Camera AI đọc biển số',plate(p)+' · '+(l?l.type:'Chưa phân loại')+' · đã chụp ảnh biển số và khuôn mặt tài xế')+st(l&&l.reg?'ok':'er','Đăng ký nhận hàng trên Web',l?(l.reg?'Đã đăng ký – '+l.driver:'Chưa đăng ký'):'Không tìm thấy biển số')+st(l&&l.ex?'ok':'er','Lô hàng đã xuất kho (COSYS)',l?(l.ex?l.id+' – Đã xuất':l.id+' – Chưa xuất'):'Không có lô hàng');
if(dup)h+=st('er','Xe đang có phiên đỗ chưa đóng','Phiên '+dup.id+' – không tạo phiên mới');
if(used)h+=st('er','Lô hàng đã nhận xong','Lô '+l.id+' đã hoàn tất, xe không được vào lại bằng lô này');
if(ok){newSess(p,l,false);S.lane.in=1;setTimeout(()=>{S.lane.in=0;if(cur=='in')R()},2500);h+=st('ok','Đủ điều kiện – tự động mở barrier','Đã lưu ảnh check-in, ghi mốc giờ vào và bắt đầu tính phí bãi')}
else{const why=!l?'Không có lô hàng/đăng ký':!l.reg?'Chưa đăng ký nhận hàng':!l.ex?'Lô hàng chưa xuất kho':dup?'Xe đang có phiên đỗ':'Lô hàng đã nhận xong';
h+=st('er','Không đủ điều kiện – barrier giữ đóng','Bảo vệ hướng dẫn xe quay đầu; chỉ khi được cấp thẩm quyền mới mở thủ công')+`<div class="row mt"><button class="s" onclick="turnIn('${p}','${why}')">Hướng dẫn quay đầu</button><button class="d" onclick="manual('${p}','vào')">Mở barrier thủ công</button></div>`}
S.last.in=p;inR=snap('in',p,l?l.type:null,ok,h,{nf:!l,why:ok?'':(!l?'Không có lô hàng / đăng ký':!l.reg?'Chưa đăng ký nhận hàng':!l.ex?'Lô hàng chưa xuất kho':dup?'Xe đang có phiên đỗ':'Lô hàng đã nhận xong')});R()};
window.turnIn=(p,w)=>{S.exc.unshift({t:now(),who:'baove01',lane:'Lane vào 1',plate:p,why:w,kind:'Quay đầu (lane vào)'});inR=null;R();toast('Đã ghi nhật ký xe quay đầu')};
window.manual=(p,d)=>{modal(`<h3>Mở barrier thủ công (remote) – ${d}</h3><p>Biển số ${plate(p)}</p><label>Mã bảo vệ</label><select id="mg"><option>baove01</option></select><label>Lý do cưỡng chế (bắt buộc)</label><textarea id="mw" rows=3 style="width:100%"></textarea><div class="row mt"><button onclick="doManual('${p}','${d}')">Xác nhận & ghi log</button><button class="s" onclick="cm()">Hủy</button></div>`)};
window.owe=s=>{const t=s.payAt&&now()-s.payAt<=GRACE*6e4?s.payAt:now();return Math.max(0,feeOf(s,t).tot-s.paid)};
window.doManual=(p,d)=>{const w=$('#mw').value.trim();if(!w)return toast('Cần nhập lý do');const l=lotBy(p);let debt=0;
if(d=='vào'){if(!live().find(s=>s.plate==p))newSess(p,l,true)}
else{const s=live().find(x=>x.plate==p);if(s){debt=owe(s);s.st='Đã đóng';s.outAt=now();s.exOut=true;s.debt=debt;if(l)l.used=true}}
S.exc.unshift({t:now(),who:$('#mg').value,lane:'Lane '+d+' 1',plate:p,why:w+(debt?' – chưa thu '+vnd(debt):''),kind:'Mở barrier thủ công ('+d+')'});inR=null;outR=null;cm();R();toast('Đã mở barrier, lưu ảnh camera và ghi log ngoại lệ')};

/* THU NGÂN */
let cs=null,qr=0;
const qrSvg=s=>{let x=0;for(const c of s)x=(x*31+c.charCodeAt(0))%1e9;let r='';for(let i=0;i<19;i++)for(let j=0;j<19;j++){x=(x*1103515245+12345)%2147483648;if(x%3<1||(i<4&&j<4)||(i<4&&j>14)||(i>14&&j<4))r+=`<rect x=${j*6} y=${i*6} width=6 height=6 />`}return`<svg viewBox="0 0 114 114" width=170 style="background:#fff;padding:6px;border-radius:6px" fill="#111">${r}</svg>`};
P.pay=()=>{const s=cs&&S.sess.find(x=>x.id==cs),unp=live().filter(x=>x.st=='Đang đỗ');
let body='<p style="color:var(--mu)">Nhập biển số hoặc quét mã kiện hàng để tra cứu.</p>';
if(s){const f=s.st=='Đang đỗ'?feeOf(s):{m:0,base:0,su:[],sf:0,tot:s.due},left=s.st=='Đang đỗ'?f.tot-s.paid:0;
body=`<div class="row">${plate(s.plate)} ${tag(s.st,s.st=='Đang đỗ'?'wa':'ok')}</div><p>Lô hàng ${s.lot} · ${s.type}<br>Giờ vào: ${fmt(s.inAt)}<br>Giờ hiện tại: ${fmt(now())}<br>Thời gian đỗ: <b>${dur(f.m)}</b></p>
<table><tr><td>Phí đỗ (${s.type})</td><td>${vnd(f.base)}</td></tr>${f.su.map(x=>`<tr><td>${x.name} (>${x.after} phút)</td><td>${vnd(x.fee)}</td></tr>`).join('')}<tr><td><b>Phải thu</b></td><td><b>${vnd(f.tot)}</b></td></tr><tr><td>Đã thanh toán</td><td>${vnd(s.paid)}</td></tr><tr><td><b>Còn lại</b></td><td><b style="color:var(--er)">${vnd(left)}</b></td></tr></table>`;
if(s.st=='Đang đỗ'){body+=`<div class="row mt"><button class="${S.tab=='QR'?'':'s'}" onclick="S.tab='QR';qr=0;R()">QR VietQR/VNPay</button><button class="${S.tab=='Cash'?'':'s'}" onclick="S.tab='Cash';R()">Tiền mặt</button></div>`;
if(S.tab=='QR')body+=`<div class="mt">${qrSvg(s.id+f.tot)}<p>Số tiền: <b>${vnd(left)}</b> · Mã GD: QR${s.id.slice(3)}${Math.floor(f.tot/1000)}</p><div class="row"><button onclick="bank('${s.id}',1)">Mô phỏng: ngân hàng báo thành công</button><button class="s" onclick="bank('${s.id}',0)">Thất bại</button></div></div>`;
else body+=`<label>Tiền khách đưa</label><input id="cash" type=number value="${Math.ceil(left/1e4)*1e4}" oninput="chg(${left})"><p>Tiền thừa: <b id="chg">${vnd(Math.ceil(left/1e4)*1e4-left)}</b></p><button onclick="cashPay('${s.id}',${left})">Xác nhận thu tiền</button>`}
else body+=`<p>Hạn ra cổng không phát sinh phí: <b>${fmt(s.payAt+GRACE*6e4)}</b></p><div class="mt"><button onclick="receipt('${s.id}')">In lại biên lai</button></div>`}
return head('Quầy thu ngân','Tra cứu phiên đỗ, tính phí tự động và thu tiền')+`<div class="g g2"><div class="c"><h3>Tra cứu xe</h3><div class="row"><select id="cp"><option value="">Chọn biển số…</option>${S.sess.filter(x=>x.st!='Đã đóng').map(x=>`<option value="${x.id}" ${x.id==cs?'selected':''}>${x.plate} · ${x.lot} (${x.st})</option>`).join('')}</select><button onclick="cs=$('#cp').value||null;R()">Tra cứu</button></div><div class="mt">${body}</div></div>
<div class="c"><h3>Xe chưa thanh toán (${unp.length})</h3>${tbl(['Biển số','Giờ vào','Tạm tính'],unp.map(x=>[`<a style="cursor:pointer;color:var(--pr)" onclick="cs='${x.id}';R()">${x.plate}</a>`,fmt(x.inAt),vnd(feeOf(x).tot)]))}</div></div>`};
window.chg=l=>$('#chg').textContent=vnd(Math.max(0,$('#cash').value-l));
function finish(s,ch,amt){const f=feeOf(s);s.due=f.tot;s.paid=f.tot;s.ch=ch;s.st='Đã thanh toán';s.payAt=now();s.rc='BL-000'+(++S.rcN);receipt(s.id)}
window.cashPay=(id,l)=>{if(+$('#cash').value<l)return toast('Tiền nhận chưa đủ');finish(S.sess.find(x=>x.id==id),'Tiền mặt')};
window.bank=(id,ok)=>{if(!ok)return toast('Ngân hàng báo thất bại – có thể tạo lại QR hoặc thu tiền mặt');finish(S.sess.find(x=>x.id==id),'QR')};
window.receipt=id=>{const s=S.sess.find(x=>x.id==id);modal(`<h3>Biên lai đã in</h3><div class="rc">CẢNG TCS – BIÊN LAI BÃI ĐỖ\nSố: ${s.rc}\nBiển số : ${s.plate}\nGiờ vào : ${fmt(s.inAt)}\nGiờ TT  : ${fmt(s.payAt)}\nHình thức: ${s.ch}\nĐã thu  : ${vnd(s.paid)}\nCòn lại : 0 đ\nXe đủ điều kiện ra cổng</div><div class="row mt"><button onclick="cm();R()">Đóng</button></div>`)};

/* LANE RA */
let outR=null;
P.out=()=>head('Kiểm soát lane ra','Camera AI đọc biển số → đối chiếu phiên vào → kiểm tra thanh toán → barrier')+`<div class="g g2"><div class="c"><h3>Mô phỏng xe tiến vào lane ra</h3><label>Biển số camera đọc được</label><div class="row"><select id="op">${live().map(s=>`<option>${s.plate}</option>`).join('')}<option>29A-999.99</option></select><button onclick="scanOut()">Camera đọc biển số</button></div><label><input type=checkbox id="of"> Mô phỏng: khuôn mặt tài xế khác ảnh lúc vào</label><p style="color:var(--mu)">Sau khi thanh toán, xe có ${GRACE} phút để ra mà không phát sinh phí. Quá hạn, hệ thống tính lại phí; nếu phí tăng thì xe bị giữ lại. Biển 29A-999.99 là xe không có phiên vào.</p><div class="mt">${pic('lane-out',laneSvg('out'),'Camera lane ra 1')}</div><div style="margin-top:12px">Barrier lane ra</div><div class="gate ${S.lane.out?'open':''}"></div></div><div class="c"><h3>Kết quả xử lý</h3>${outR||waitR('out')}</div></div>`;
window.scanOut=()=>{const p=$('#op').value,face=$('#of').checked,s=live().find(x=>x.plate==p);let pass=false,why='';let h=st('ok','Camera AI đọc biển số lane ra',plate(p)+' · chụp ảnh biển số và khuôn mặt check-out'),btn='';
if(!s){why='Không có phiên vào tương ứng';h+=st('er','Không có phiên vào tương ứng','Barrier giữ đóng – bảo vệ kiểm tra thủ công');btn=`<button class="d" onclick="manual('${p}','ra')">Mở barrier thủ công</button>`}
else{const o=owe(s);h+=st('ok','Đối chiếu phiên vào','Phiên '+s.id+' · vào lúc '+fmt(s.inAt)+' · lô '+s.lot);
h+=st(face?'er':'ok','So khớp khuôn mặt check-in / check-out',face?'Không khớp – nghi hoán đổi tài xế':'Khớp');
if(o>0&&s.st=='Đã thanh toán'){s.st='Đang đỗ'}
h+=st(o?'er':'ok','Kiểm tra thanh toán',o?(s.paid?'Còn nợ phát sinh (quá '+GRACE+' phút sau thanh toán): ':'Chưa thanh toán – phải thu ')+vnd(o):'Đã thanh toán đủ (còn lại 0 đ)');
if(!o&&!face){pass=true;s.st='Đã đóng';s.outAt=now();s.imgOut=1;const l=lotBy(p);if(l)l.used=true;S.lane.out=1;setTimeout(()=>{S.lane.out=0;if(cur=='out')R()},2500);h+=st('ok','Đạt điều kiện cho ra – tự động mở barrier','Đã ghi giờ ra, lưu ảnh check-out, đóng phiên '+s.id)}
else{why=o?'Còn phải thu '+vnd(o)+' · quay lại quầy':'Khuôn mặt không khớp ảnh check-in';h+=st('er','Không đạt – barrier giữ đóng','Cảnh báo bảo vệ: '+(o?'hướng dẫn tài xế quay lại quầy thanh toán':'xác minh danh tính tài xế'));if(o)S.alerts.unshift({t:now(),plate:p,owe:o}),btn=`<button class="s" onclick="turn('${p}')">Xe quay lại quầy</button> `;btn+=`<button class="d" onclick="manual('${p}','ra')">Mở barrier thủ công</button>`}}
S.last.out=p;outR=snap('out',p,s?s.type:null,pass,h+(btn?`<div class="row mt">${btn}</div>`:''),{face,why,nf:!s&&!lotBy(p)});R()};
window.turn=p=>{const s=live().find(x=>x.plate==p);S.exc.unshift({t:now(),who:'baove01',lane:'Lane ra 1',plate:p,why:'Chưa thanh toán đủ, còn '+vnd(owe(s)),kind:'Quay lại quầy thanh toán'});outR=null;cs=s.id;go('pay');toast('Đã ghi nhật ký và chuyển sang quầy thu ngân')};

/* DANH MỤC */
P.lots=()=>head('Danh mục lô hàng','Đồng bộ từ COSYS, chu kỳ 5 phút/lần','<button onclick="sync()">Đồng bộ ngay</button>')+`<div class="c">${tbl(['Mã lô','Biển số','Loại xe','Xuất kho','Đăng ký web','Đồng bộ lúc'],S.lots.map(l=>[l.id,l.plate,l.type,tag(l.ex?'Đã xuất':'Chưa xuất',l.ex?'ok':'wa'),tag(l.reg?'Đã đăng ký':'Chưa đăng ký',l.reg?'ok':'wa'),fmt(S.lots.sy||now()-3e5)]))}</div>`;
window.sync=()=>{S.lots.sy=now();S.api.unshift({t:now(),sys:'COSYS',ip:'10.10.1.5',ok:true,msg:'OK – '+S.lots.length+' bản ghi'});toast('Đã đồng bộ COSYS thành công');R()};
P.recv=()=>head('Thông tin nhận hàng','Tài xế, chủ hàng và tình trạng đăng ký (dữ liệu từ web đăng ký lấy hàng)')+`<div class="c">${tbl(['Lô hàng','Biển số','Tài xế','Chủ hàng','Tình trạng đăng ký','Đủ điều kiện vào'],S.lots.map(l=>[l.id,l.plate,l.driver,l.owner,tag(l.reg?'Đã đăng ký':'Chưa đăng ký',l.reg?'ok':'wa'),l.reg&&l.ex?tag('Đạt','ok'):tag('Không đạt','er')]))}</div>`;

/* GIÁ */
P.prices=()=>head('Bảng giá sân đỗ','Khung giá theo loại xe và thời gian đỗ','<button onclick="edP()">+ Thêm khung giá</button>')+`<div class="c">${tbl(['Mã','Loại xe','Từ (phút)','Đến (phút)','Đơn giá',''],S.prices.map((p,i)=>[p.id,p.type,p.from,p.to>9e4?'∞':p.to,vnd(p.price),`<button class="s" onclick="edP(${i})">Sửa</button> <button class="s" onclick="S.prices.splice(${i},1);R()">Xóa</button>`]))}</div>`;
window.edP=i=>{const p=S.prices[i]||{id:'BG-'+(S.prices.length+1),type:TYPES[0],from:0,to:60,price:0};modal(`<h3>${i>=0?'Sửa':'Thêm'} khung giá</h3><label>Loại xe</label><select id="pt">${TYPES.map(t=>`<option ${t==p.type?'selected':''}>${t}</option>`).join('')}</select><label>Từ (phút)</label><input id="pf" type=number value=${p.from}><label>Đến (phút)</label><input id="pto" type=number value=${p.to}><label>Đơn giá (đ)</label><input id="pp" type=number value=${p.price}><div class="row mt"><button onclick="svP(${i>=0?i:-1},'${p.id}')">Lưu</button><button class="s" onclick="cm()">Hủy</button></div>`)};
window.svP=(i,id)=>{const o={id,type:$('#pt').value,from:+$('#pf').value,to:+$('#pto').value,price:+$('#pp').value};if(o.to<=o.from)return toast('Khoảng thời gian không hợp lệ');i<0?S.prices.push(o):S.prices[i]=o;cm();R();toast('Đã lưu bảng giá')};
P.sur=()=>head('Phụ phí dịch vụ','Phụ phí tự động cộng vào tổng phải thu','<button onclick="edS()">+ Thêm phụ phí</button>')+`<div class="c">${tbl(['Mã','Loại phụ phí','Ngưỡng (phút)','Mức thu','Áp dụng',''],S.sur.map((p,i)=>[p.id,p.name,'> '+p.after,vnd(p.fee),tag(p.on?'Bật':'Tắt',p.on?'ok':''),`<button class="s" onclick="S.sur[${i}].on^=1;R()">${p.on?'Tắt':'Bật'}</button> <button class="s" onclick="S.sur.splice(${i},1);R()">Xóa</button>`]))}</div>`;
window.edS=()=>modal(`<h3>Thêm phụ phí</h3><label>Tên</label><input id="sn"><label>Ngưỡng thời gian (phút)</label><input id="sa" type=number value=180><label>Mức phụ thu (đ)</label><input id="sf" type=number value=50000><div class="row mt"><button onclick="if(!$('#sn').value)return toast('Nhập tên');S.sur.push({id:'PP-0'+(S.sur.length+1),name:$('#sn').value,after:+$('#sa').value,fee:+$('#sf').value,on:1});cm();R()">Lưu</button><button class="s" onclick="cm()">Hủy</button></div>`);

/* QUẢN TRỊ */
const PERM={'Bảo vệ cổng':'Lane vào, lane ra, mở barrier thủ công','Thu ngân quầy':'Tra cứu, thu tiền, in biên lai','Quản lý an ninh':'Xem lịch sử, báo cáo, bảng giá','Quản trị hệ thống':'Toàn quyền, phân quyền, kết nối API'};
P.users=()=>head('Phân quyền người dùng','4 vai trò: bảo vệ, thu ngân, quản lý an ninh, quản trị','<button onclick="edU()">+ Thêm người dùng</button>')+`<div class="g g2"><div class="c">${tbl(['Tài khoản','Họ tên','Vai trò','Trạng thái',''],S.users.map((u,i)=>[u.u,u.n,u.r,tag(u.on?'Hoạt động':'Khóa',u.on?'ok':'er'),`<button class="s" onclick="S.users[${i}].on^=1;R()">${u.on?'Khóa':'Mở khóa'}</button>`]))}</div><div class="c"><h3>Quyền theo vai trò</h3>${Object.entries(PERM).map(([r,p])=>st('ok',r,p)).join('')}</div></div>`;
window.edU=()=>modal(`<h3>Thêm người dùng</h3><label>Tên đăng nhập</label><input id="un"><label>Họ tên</label><input id="uf"><label>Vai trò</label><select id="ur">${Object.keys(PERM).map(r=>`<option>${r}</option>`).join('')}</select><div class="row mt"><button onclick="if(!$('#un').value)return toast('Nhập tên đăng nhập');S.users.push({u:$('#un').value,n:$('#uf').value,r:$('#ur').value,on:1});cm();R()">Lưu</button><button class="s" onclick="cm()">Hủy</button></div>`);

P.hist=()=>{const q=hf.toLowerCase(),ss=S.sess.filter(s=>s.plate.toLowerCase().includes(q)),ee=S.exc.filter(e=>e.plate.toLowerCase().includes(q));
return head('Lịch sử giám sát & ngoại lệ','Tra cứu vào/ra, thanh toán và mở barrier thủ công')+`<div class="c"><div class="row"><input id="hq" placeholder="Lọc theo biển số" value="${hf}"><button onclick="hf=$('#hq').value;R()">Tìm</button></div></div><div class="c mt"><h3>Lịch sử vào/ra & thanh toán</h3>${tbl(['Phiên','Biển số','Vào','Ra','Thanh toán','Hình thức','Trạng thái'],ss.map(s=>[s.id,s.plate,fmt(s.inAt),fmt(s.outAt),s.paid?vnd(s.paid):'—',s.ch||'—',tag(s.st)+(s.exIn||s.exOut?' '+tag('Ngoại lệ','er'):'')]))}</div><div class="c mt"><h3>Nhật ký ngoại lệ (mở thủ công, quay đầu, quay lại quầy)</h3>${tbl(['Thời điểm','Loại','Lane','Biển số','Mã bảo vệ','Lý do','Ảnh'],ee.map(e=>[fmt(e.t),e.kind,e.lane,e.plate,e.who,e.why,'📷 đã lưu']))}</div>`};
P.api=()=>head('Kết nối API','Trạng thái tích hợp COSYS, Camera AI, Banking Gateway')+`<div class="g g4">${[['COSYS','10.10.1.5','Online'],['Camera AI','10.10.2.21','Online'],['Radar lane vào','10.10.2.30','Online'],['Barrier lane ra','10.10.2.41','Online']].map(a=>`<div class="c k"><b style="font-size:16px">${a[0]}</b><span>${a[1]}</span><div>${tag(a[2],'ok')}</div></div>`).join('')}</div><div class="c mt"><h3>Nhật ký gọi API</h3>${tbl(['Thời gian','Hệ thống','IP','Kết quả','Chi tiết'],S.api.map(a=>[fmt(a.t),a.sys,a.ip,tag(a.ok?'Thành công':'Thất bại',a.ok?'ok':'er'),a.msg]))}</div>`;

/* BÁO CÁO */
P.rev=()=>{const d=[['T2',6.2],['T3',7.1],['T4',5.8],['T5',8.4],['T6',9.3],['T7',7.7],['CN',4.1]],ca=[['Ca sáng',9.8],['Ca chiều',8.6],['Ca đêm',3.2]];
return head('Báo cáo doanh thu','Theo ngày, ca và kênh thanh toán','<button class="s" onclick="toast(\'Đã xuất file Excel\')">Xuất Excel</button><button class="s" onclick="toast(\'Đã xuất file PDF\')">Xuất PDF</button>')+`<div class="g g2"><div class="c"><h3>Doanh thu 7 ngày (triệu đồng)</h3>${bars(d,x=>x.toFixed(1))}</div><div class="c"><h3>Theo ca (triệu đồng)</h3>${bars(ca,x=>x.toFixed(1))}<h3 class="mt">Theo kênh thanh toán</h3>${bars([['QR',14.6],['Tiền mặt',7.0]],x=>x.toFixed(1))}</div></div>`};
P.trf=()=>{const h=[['06h',12],['08h',34],['10h',41],['12h',22],['14h',38],['16h',45],['18h',19]];
return head('Báo cáo lưu lượng xe','Xe ra vào và mở barrier thủ công','<button class="s" onclick="toast(\'Đã xuất báo cáo\')">Xuất báo cáo</button>')+`<div class="g g2"><div class="c"><h3>Lượt xe vào theo khung giờ</h3>${bars(h)}</div><div class="c"><h3>Tổng hợp</h3>${st('ok','Xe vào hôm nay',String(211+S.sess.length))}${st('ok','Xe ra hôm nay','204')}${st(S.exc.filter(e=>e.kind.startsWith('Mở')).length?'wa':'ok','Mở barrier thủ công',S.exc.filter(e=>e.kind.startsWith('Mở')).length+' lượt – cần kiểm tra lý do')}</div></div>`};

/* ===== v3: đăng nhập, phân quyền, màn hình con ===== */
let me=null,lf={q:'',s:''},hf={q:'',a:'',b:'',k:'',g:''},tf='';S.iv=5;S.last={in:'—',out:'—'};S.alerts=[];
S.dev=[{n:'COSYS',ip:'10.10.1.5',st:'Online'},{n:'Camera AI (ALPR)',ip:'10.10.2.21',st:'Online'},{n:'Radar lane vào',ip:'10.10.2.30',st:'Online'},{n:'Barrier lane ra',ip:'10.10.2.41',st:'Online'},{n:'Banking Gateway',ip:'gw.bank.local',st:'Online'}];
const ALL=MENU.flatMap(g=>g[1].map(x=>x[0]));
S.perm={'Bảo vệ cổng':['in','out','mon','alert'],'Thu ngân quầy':['pay','txn','alert'],'Quản lý an ninh':['in','out','mon','alert','lots','recv','pay','txn','prices','sur','hist','rev','trf'],'Quản trị hệ thống':ALL};
const can=k=>k=='dash'||S.perm[me.r].includes(k),vis=()=>me?MENU.map(([g,a])=>[g,a.filter(x=>can(x[0]))]).filter(x=>x[1].length):[],foot=()=>me?`<h6>Tài khoản</h6><a onclick="me=null;go('dash')">${me.n}<br><small>${me.r} – Đăng xuất</small></a>`:'';
P.login=()=>`<div style="max-width:520px;margin:6vh auto"><div class="c"><h2 style="margin-top:0">Đăng nhập HTQLAN</h2><p style="color:var(--mu)">Chọn tài khoản để vào theo vai trò (bản demo, không cần mật khẩu). Menu thay đổi theo quyền.</p>${S.users.filter(u=>u.on).map(u=>`<div class="step" style="cursor:pointer" tabindex=0 onclick="login('${u.u}')"><div><b>${u.n}</b><div style="color:var(--mu)">${u.u} · ${u.r}</div></div></div>`).join('')}</div></div>`;
window.login=u=>{me=S.users.find(x=>x.u==u);go(vis()[0][1][0][0])};
P.deny=()=>head('Không có quyền truy cập','Vai trò '+me.r+' không được dùng chức năng này. Liên hệ quản trị hệ thống.');
const imgP=p=>pic('plates/'+p,plSvg(p),'Ảnh biển số','s'),imgF=(t,id='x')=>pic('faces/'+id+'-'+(/out/.test(t)?'out':'in'),faceSvg(),t,'s');
const kv=a=>`<table>${a.map(([k,v])=>`<tr><td style="color:var(--mu)">${k}</td><td>${v}</td></tr>`).join('')}</table>`;
window.sessD=id=>{const s=S.sess.find(x=>x.id==id),e=s.outAt||s.payAt||now();modal(`<h3>Phiên ${s.id}</h3><div class="row">${imgP(s.plate)}${imgF('Tài xế – check-in',s.id)}${s.outAt?imgF('Tài xế – check-out',s.id):''}</div>`+kv([['Biển số',s.plate],['Loại xe / Lô hàng',s.type+' / '+s.lot],['Giờ vào',fmt(s.inAt)],['Giờ thanh toán',fmt(s.payAt)],['Giờ ra',fmt(s.outAt)],['Tổng thời gian đỗ',dur(Math.ceil((e-s.inAt)/6e4))],['Đã thu',s.paid?vnd(s.paid)+' ('+s.ch+')':'—'],['Biên lai',s.rc||'—'],['Ngoại lệ',s.exIn?'Vào bằng mở thủ công':s.exOut?'Ra bằng mở thủ công, chưa thu '+vnd(s.debt||0):'Không']])+`<div class="row mt"><button onclick="cm()">Đóng</button></div>`)};
/* Giám sát */
P.mon=()=>{const ln=(n,k,d)=>{const p=S.last[k],l=lotBy(p),op=S.lane[k];return`<div class="c"><h3>${n}</h3>${pic('lane-'+k,laneSvg(k),n+' – camera')}<div class="row mt">${imgP(p)}${imgF('Tài xế')}</div>`+kv([['Radar',tag(op?'Vehicle Present':'Clear',op?'wa':'ok')],['Camera ALPR / góc rộng',tag('Online','ok')],['Barrier',tag(op?'Đang mở':'Đóng',op?'ok':'er')],['Biển số gần nhất',p],['Phân loại phương tiện',l?l.type+' · tải trọng đăng ký 15 tấn':'Chưa phân loại']])+`<div class="row mt"><button class="s" onclick="go('${k}')">Mở màn hình kiểm soát</button><button class="d" onclick="manual('${p}','${d}')">Mở barrier thủ công</button></div></div>`};
return head('Giám sát camera & radar','Tín hiệu radar, ảnh biển số, chân dung tài xế và trạng thái barrier từng lane')+`<div class="g g2">${ln('Lane vào 1','in','vào')}${ln('Lane ra 1','out','ra')}</div>`};
/* Giao dịch */
P.txn=()=>{const L=S.sess.filter(x=>x.rc&&(!tf||x.ch==tf)),t=L.reduce((a,x)=>a+x.paid,0);return head('Giao dịch thanh toán','Mốc giờ vào, giờ thanh toán, tổng thời gian đỗ và mã giao dịch')+`<div class="c"><div class="row"><select id="tc"><option value="">Tất cả kênh</option><option ${tf=='QR'?'selected':''}>QR</option><option ${tf=='Tiền mặt'?'selected':''}>Tiền mặt</option></select><button onclick="tf=$('#tc').value;R()">Lọc</button><b>Tổng: ${vnd(t)}</b></div></div><div class="c mt">${tbl(['Mã GD','Biển số','Mã kiện','Giờ vào','Giờ thanh toán','Đỗ','Đã thu','Kênh',''],L.map(x=>[x.rc,x.plate,x.lot,fmt(x.inAt),fmt(x.payAt),dur(Math.ceil((x.payAt-x.inAt)/6e4)),vnd(x.paid),x.ch,`<button class="s" onclick="sessD('${x.id}')">Chi tiết</button>`]))}</div>`};
/* Cảnh báo */
P.alert=()=>head('Cảnh báo xe chưa thanh toán','Xe bị giữ barrier ở lane ra và nhật ký quay đầu')+`<div class="c">${tbl(['Thời điểm','Biển số','Còn phải thu','Trạng thái',''],S.alerts.map(a=>{const x=live().find(s=>s.plate==a.plate),o=x?owe(x):0;return[fmt(a.t),a.plate,vnd(a.owe),x?tag(o?'Chờ thanh toán':'Đã thanh toán – cho ra',o?'er':'ok'):tag('Đã xử lý','ok'),x&&o?`<button class="s" onclick="cs='${x.id}';go('pay')">Chuyển thu ngân</button>`:'']}))}</div><div class="c mt"><h3>Nhật ký quay đầu / quay lại quầy</h3>${tbl(['Thời điểm','Lane','Biển số','Lý do'],S.exc.filter(e=>!e.kind.startsWith('Mở')).map(e=>[fmt(e.t),e.lane,e.plate,e.why]))}</div>`;
/* Lô hàng + đồng bộ */
P.lots=()=>{const q=lf.q.toLowerCase(),L=S.lots.filter(l=>(l.plate+l.id).toLowerCase().includes(q)&&(!lf.s||(lf.s=='ok')==!!(l.ex&&l.reg&&!l.used)));return head('Danh mục lô hàng','Đồng bộ từ COSYS, chu kỳ '+S.iv+' phút/lần','<button onclick="sync()">Đồng bộ ngay</button><button class="s" onclick="ivM()">Cấu hình đồng bộ</button>')+`<div class="c"><div class="row"><input id="lq" placeholder="Mã lô / biển số" value="${lf.q}"><select id="ls"><option value="">Tất cả</option><option value="ok" ${lf.s=='ok'?'selected':''}>Đủ điều kiện vào</option><option value="no" ${lf.s=='no'?'selected':''}>Chưa đủ điều kiện</option></select><button onclick="lf={q:$('#lq').value,s:$('#ls').value};R()">Lọc</button></div></div><div class="c mt">${tbl(['Mã lô','Biển số','Loại xe','Xuất kho','Đăng ký web','Đồng bộ lúc',''],L.map(l=>[l.id,l.plate,l.type,tag(l.used?'Đã nhận xong':l.ex?'Đã xuất':'Chưa xuất',l.used||l.ex?'ok':'wa'),tag(l.reg?'Đã đăng ký':'Chưa đăng ký',l.reg?'ok':'wa'),fmt(S.lots.sy||now()-3e5),`<button class="s" onclick="lotD('${l.id}')">Chi tiết</button>`]))}</div><div class="c mt"><h3>Nhật ký đồng bộ COSYS</h3>${tbl(['Thời gian','Kết quả','Chi tiết'],S.api.filter(a=>a.sys=='COSYS').slice(0,5).map(a=>[fmt(a.t),tag(a.ok?'Thành công':'Thất bại',a.ok?'ok':'er'),a.msg]))}</div>`};
window.ivM=()=>modal(`<h3>Cấu hình đồng bộ COSYS</h3><label>Chu kỳ truy vấn API</label><select id="iv">${[1,5,10,15].map(v=>`<option ${v==S.iv?'selected':''} value=${v}>${v} phút/lần</option>`).join('')}</select><div class="row mt"><button onclick="S.iv=+$('#iv').value;cm();R();toast('Đã lưu chu kỳ đồng bộ')">Lưu</button><button class="s" onclick="cm()">Hủy</button></div>`);
window.lotD=id=>{const l=S.lots.find(x=>x.id==id),s=S.sess.find(x=>x.lot==id);modal(`<h3>Lô hàng ${l.id}</h3>`+kv([['Biển số',l.plate],['Loại xe',l.type],['Chủ hàng',l.owner],['Tài xế',l.driver],['Xuất kho',l.ex?'Đã xuất':'Chưa xuất'],['Đăng ký web',l.reg?'Đã đăng ký':'Chưa đăng ký'],['Điều kiện vào',l.ex&&l.reg&&!l.used?'Đạt':'Không đạt'],['Phiên bãi',s?s.id+' – '+s.st:'Chưa có']])+`<div class="row mt">${s?`<button class="s" onclick="cm();sessD('${s.id}')">Xem phiên</button>`:''}<button onclick="cm()">Đóng</button></div>`)};
/* Nhận hàng */
P.recv=()=>head('Thông tin nhận hàng','Tài xế, chủ hàng và tình trạng đăng ký (từ web đăng ký lấy hàng)','<button onclick="recvE(-1)">+ Đăng ký nhận hàng (mô phỏng web)</button>')+`<div class="c">${tbl(['Lô hàng','Biển số','Tài xế','Chủ hàng','Đăng ký','Đủ điều kiện vào',''],S.lots.map((l,i)=>[l.id,l.plate,l.driver,l.owner,tag(l.reg?'Đã đăng ký':'Chưa đăng ký',l.reg?'ok':'wa'),l.reg&&l.ex&&!l.used?tag('Đạt','ok'):tag('Không đạt','er'),`<button class="s" onclick="recvE(${i})">Sửa</button>`]))}</div>`;
window.recvE=i=>{const l=S.lots[i]||{plate:'',type:TYPES[0],ex:0,reg:1,driver:'',owner:''},o=(a,v)=>a.map(x=>`<option value="${x[0]}" ${x[0]==v?'selected':''}>${x[1]}</option>`).join('');modal(`<h3>${i>=0?'Sửa '+l.id:'Đăng ký nhận hàng mới'}</h3><label>Biển số</label><input id="rp" value="${l.plate}"><label>Loại xe</label><select id="rt">${TYPES.map(t=>`<option ${t==l.type?'selected':''}>${t}</option>`).join('')}</select><label>Tài xế</label><input id="rd" value="${l.driver}"><label>Chủ hàng</label><input id="ro" value="${l.owner}"><label>Đăng ký web</label><select id="rr">${o([[1,'Đã đăng ký'],[0,'Chưa đăng ký']],l.reg)}</select><label>Xuất kho (mô phỏng dữ liệu COSYS)</label><select id="rx">${o([[1,'Đã xuất'],[0,'Chưa xuất']],l.ex)}</select><div class="row mt"><button onclick="svR(${i})">Lưu</button><button class="s" onclick="cm()">Hủy</button></div>`)};
window.svR=i=>{const p=$('#rp').value.trim().toUpperCase();if(!p)return toast('Nhập biển số');const o=Object.assign(S.lots[i]||{id:'LH-'+(2601+S.lots.length),sync:'Đã đồng bộ'},{plate:p,type:$('#rt').value,driver:$('#rd').value||'—',owner:$('#ro').value,reg:+$('#rr').value,ex:+$('#rx').value});if(i<0)S.lots.push(o);cm();R();toast('Đã lưu – lane vào dùng dữ liệu mới ngay');};
/* Lịch sử */
P.hist=()=>{const q=hf.q.toLowerCase(),a=hf.a?new Date(hf.a).getTime():0,b=hf.b?new Date(hf.b).getTime()+864e5:9e15,ss=S.sess.filter(x=>x.plate.toLowerCase().includes(q)&&x.inAt>=a&&x.inAt<b),ee=S.exc.filter(e=>e.plate.toLowerCase().includes(q)&&e.t>=a&&e.t<b&&(!hf.k||e.kind==hf.k)&&(!hf.g||e.who==hf.g)),ks=[...new Set(S.exc.map(e=>e.kind))],gs=[...new Set(S.exc.map(e=>e.who))],op=(l,v)=>l.map(x=>`<option ${x==v?'selected':''}>${x}</option>`).join('');
return head('Lịch sử giám sát & ngoại lệ','Tra cứu ảnh vào/ra, thanh toán và mở barrier thủ công')+`<div class="c"><div class="row"><input id="hq" placeholder="Biển số" value="${hf.q}"><input id="ha" type=date value="${hf.a}"><input id="hb" type=date value="${hf.b}"><select id="hk"><option value="">Mọi loại ngoại lệ</option>${op(ks,hf.k)}</select><select id="hg"><option value="">Mọi mã bảo vệ</option>${op(gs,hf.g)}</select><button onclick="hf={q:$('#hq').value,a:$('#ha').value,b:$('#hb').value,k:$('#hk').value,g:$('#hg').value};R()">Tìm</button><button class="s" onclick="hf={q:'',a:'',b:'',k:'',g:''};R()">Xóa lọc</button></div></div><div class="c mt"><h3>Lịch sử vào/ra & thanh toán (${ss.length})</h3>${tbl(['Phiên','Biển số','Vào','Ra','Thanh toán','Kênh','Trạng thái',''],ss.map(x=>[x.id,x.plate,fmt(x.inAt),fmt(x.outAt),x.paid?vnd(x.paid):'—',x.ch||'—',tag(x.st)+(x.exIn||x.exOut?' '+tag('Ngoại lệ','er'):''),`<button class="s" onclick="sessD('${x.id}')">Xem ảnh & chi tiết</button>`]))}</div><div class="c mt"><h3>Nhật ký ngoại lệ (${ee.length})</h3>${tbl(['Thời điểm','Loại','Lane','Biển số','Mã bảo vệ','Lý do',''],ee.map(e=>[fmt(e.t),e.kind,e.lane,e.plate,e.who,e.why,`<button class="s" onclick="excD(${S.exc.indexOf(e)})">Xem ảnh</button>`]))}</div>`};
window.excD=i=>{const e=S.exc[i];modal(`<h3>Sự kiện ngoại lệ</h3><div class="row">${imgP(e.plate)}${imgF('Ảnh khi kích hoạt')}</div>`+kv([['Loại',e.kind],['Thời điểm',fmt(e.t)],['Lane',e.lane],['Mã bảo vệ',e.who],['Lý do',e.why]])+`<div class="row mt"><button onclick="cm()">Đóng</button></div>`)};
/* API */
P.api=()=>head('Kết nối API','Trạng thái tích hợp COSYS, Camera AI, radar, barrier và Banking Gateway')+`<div class="g g4">${S.dev.map((d,i)=>`<div class="c k"><b style="font-size:16px">${d.n}</b><span>${d.ip}</span><div>${tag(d.st,d.st=='Online'?'ok':'er')}</div><div class="row mt"><button class="s" onclick="tst(${i},1)">Kiểm tra</button><button class="s" onclick="tst(${i},0)">Giả lập lỗi</button></div></div>`).join('')}</div><div class="c mt"><h3>Nhật ký gọi API</h3>${tbl(['Thời gian','Hệ thống','IP','Kết quả','Chi tiết'],S.api.map(a=>[fmt(a.t),a.sys,a.ip,tag(a.ok?'Thành công':'Thất bại',a.ok?'ok':'er'),a.msg]))}</div>`;
window.tst=(i,ok)=>{const d=S.dev[i];d.st=ok?'Online':'Error';S.api.unshift({t:now(),sys:d.n,ip:d.ip,ok:!!ok,msg:ok?'Ping OK – 42 ms':'Timeout 30s'});R();toast(ok?'Kết nối '+d.n+' bình thường':'Cảnh báo: '+d.n+' mất kết nối')};
/* Phân quyền + báo cáo */
const _u=P.users;P.users=()=>_u()+`<div class="c mt"><h3>Ma trận phân quyền theo chức năng</h3>${tbl(['Chức năng',...Object.keys(PERM)],MENU.flatMap(g=>g[1]).map(([k,n])=>[n,...Object.keys(PERM).map((r,j)=>`<input type=checkbox ${S.perm[r].includes(k)?'checked':''} ${j==3?'disabled':''} onchange="tp(${j},'${k}')">`)]))}</div>`;
window.tp=(j,k)=>{const a=S.perm[Object.keys(PERM)[j]],i=a.indexOf(k);i<0?a.push(k):a.splice(i,1);toast('Đã cập nhật quyền – áp dụng khi đăng nhập lại')};
const _r=P.rev;P.rev=()=>{const p=S.sess.filter(x=>x.rc),f=c=>vnd(p.filter(x=>x.ch==c).reduce((a,x)=>a+x.paid,0));return _r()+`<div class="c mt"><h3>Chi tiết giao dịch trong phiên làm việc</h3><p>QR: <b>${f('QR')}</b> · Tiền mặt: <b>${f('Tiền mặt')}</b></p>${tbl(['Biên lai','Biển số','Kênh','Số tiền','Giờ thu'],p.map(x=>[x.rc,x.plate,x.ch,vnd(x.paid),fmt(x.payAt)]))}</div>`};
const _t=P.trf;P.trf=()=>{const k={};S.exc.forEach(e=>k[e.kind]=(k[e.kind]||0)+1);return _t()+`<div class="c mt"><h3>Thống kê ngoại lệ theo loại</h3>${bars(Object.entries(k))}</div>`};

window.logout=()=>{me=null;inR=null;outR=null;cs=null;go('dash')};

/* ===== v4: giao diện sáng/tối, thương hiệu, ảnh thực tế ===== */
const isDark=()=>document.documentElement.dataset.theme?document.documentElement.dataset.theme=='dark':matchMedia('(prefers-color-scheme:dark)').matches;
window.tt=()=>{const t=isDark()?'light':'dark';document.documentElement.dataset.theme=t;try{localStorage.setItem('tcs-theme',t)}catch(e){}R()};
const pic=(slot,fb,cap,cls='')=>`<figure class="pic ${cls}">${CFG.photos?`<img src="assets/img/photos/${slot}.jpg" alt="${cap}" data-fb="${fb.replace(/"/g,'&quot;')}" onerror="this.outerHTML=this.dataset.fb">`:fb}<figcaption>${cap}</figcaption></figure>`;
const plSvg=p=>`<svg viewBox="0 0 150 90"><rect width="150" height="90" fill="#232b3d"/><rect y="66" width="150" height="24" fill="#0f1420"/><rect x="14" y="26" width="122" height="36" rx="5" fill="#f2c530" stroke="#222" stroke-width="2"/><circle cx="22" cy="44" r="2" fill="#555"/><circle cx="128" cy="44" r="2" fill="#555"/><text x="75" y="52" text-anchor="middle" font-family="Arial,sans-serif" font-weight="700" font-size="19" fill="#111" letter-spacing="1">${p}</text></svg>`;
const faceSvg=()=>`<svg viewBox="0 0 150 90"><rect width="150" height="90" fill="#31405f"/><rect x="8" y="8" width="134" height="74" rx="8" fill="#5f7da3" opacity=".5"/><circle cx="75" cy="38" r="15" fill="#c8a586"/><path d="M40 82c2-20 16-26 35-26s33 6 35 26z" fill="#f5c400"/></svg>`;
const laneSvg=k=>`<svg viewBox="0 0 320 130"><rect width="320" height="130" fill="#8fb3cf"/><rect width="320" height="42" fill="#b9d2e4"/><rect y="84" width="320" height="46" fill="#3a3f49"/><path d="M0 108h320" stroke="#e8e8e8" stroke-width="2" stroke-dasharray="16 10"/><rect x="24" y="36" width="10" height="56" fill="#d4d8de"/><rect x="34" y="40" width="112" height="7" fill="#f58220"/><rect x="262" y="14" width="8" height="78" fill="#59627a"/><rect x="246" y="12" width="34" height="16" rx="3" fill="#20283a"/><circle cx="256" cy="20" r="4" fill="#5cc8ff"/><g transform="translate(${k=='in'?170:190} 62)"><rect width="70" height="34" rx="3" fill="#f5f5f5"/><rect x="70" y="8" width="26" height="26" rx="3" fill="#1b6a8a"/><circle cx="16" cy="36" r="7" fill="#111"/><circle cx="80" cy="36" r="7" fill="#111"/></g><text x="8" y="123" font-size="9" fill="#fff" font-family="Arial">Hình minh họa – thay bằng ảnh camera thực</text></svg>`;
const heroH=()=>`<div class="hero hero-main"><img src="${IMG.banner}" alt="Máy bay Vietnam Airlines đang xếp container hàng hóa ULD tại sân đỗ"><div><b>TCS – Dịch vụ Hàng hóa Tân Sơn Nhất</b><br>Hệ thống quản lý an ninh cổng lane vào / lane ra khu vực nhận hàng · 46–48 Hậu Giang, TP.HCM</div><small class="cr">Ảnh: Bahnfrend / Wikimedia Commons, CC BY-SA 4.0</small></div>`;
P.login=()=>`<div style="max-width:660px;margin:3vh auto"><div class="row" style="justify-content:space-between;margin-bottom:10px"><span class="logobox"><img src="${IMG.logo}" alt="TCS – Experience Beyond Cargo"></span><button class="s" onclick="tt()">◐ Sáng/Tối</button></div>${heroH()}<div class="c"><h2 style="margin-top:0">Đăng nhập hệ thống quản lý an ninh cổng</h2><p style="color:var(--mu)">Chọn tài khoản để vào theo vai trò (bản demo, không cần mật khẩu). Menu thay đổi theo quyền.</p>${S.users.filter(u=>u.on).map(u=>`<div class="step" style="cursor:pointer" tabindex=0 onclick="login('${u.u}')"><div><b>${u.n}</b><div style="color:var(--mu)">${u.u} · ${u.r}</div></div></div>`).join('')}</div></div>`;
go(location.hash.slice(1)&&P[location.hash.slice(1)]?location.hash.slice(1):'dash');
